language: ruby
rvm:
  - 2.4.1
cache: bundler
services:
- postgresql
addons:
- postgresql: '11.5'
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rspec
